// Code generated by protoc-gen-go. DO NOT EDIT.
// source: article.proto

/*
Package article is a generated protocol buffer package.

It is generated from these files:
	article.proto

It has these top-level messages:
	Article
	ArticleListRequest
	ArticleListResponse
*/
package article

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Article struct {
	Id          int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	CreatAt     string `protobuf:"bytes,4,opt,name=creatAt" json:"creatAt,omitempty"`
}

func (m *Article) Reset()                    { *m = Article{} }
func (m *Article) String() string            { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()               {}
func (*Article) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Article) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Article) GetCreatAt() string {
	if m != nil {
		return m.CreatAt
	}
	return ""
}

type ArticleListRequest struct {
	Page     int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	Pagesize int32 `protobuf:"varint,2,opt,name=pagesize" json:"pagesize,omitempty"`
}

func (m *ArticleListRequest) Reset()                    { *m = ArticleListRequest{} }
func (m *ArticleListRequest) String() string            { return proto.CompactTextString(m) }
func (*ArticleListRequest) ProtoMessage()               {}
func (*ArticleListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ArticleListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ArticleListRequest) GetPagesize() int32 {
	if m != nil {
		return m.Pagesize
	}
	return 0
}

type ArticleListResponse struct {
	Article []*Article `protobuf:"bytes,4,rep,name=article" json:"article,omitempty"`
}

func (m *ArticleListResponse) Reset()                    { *m = ArticleListResponse{} }
func (m *ArticleListResponse) String() string            { return proto.CompactTextString(m) }
func (*ArticleListResponse) ProtoMessage()               {}
func (*ArticleListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ArticleListResponse) GetArticle() []*Article {
	if m != nil {
		return m.Article
	}
	return nil
}

func init() {
	proto.RegisterType((*Article)(nil), "Article")
	proto.RegisterType((*ArticleListRequest)(nil), "ArticleListRequest")
	proto.RegisterType((*ArticleListResponse)(nil), "ArticleListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ArticleService service

type ArticleServiceClient interface {
	ArticleList(ctx context.Context, in *ArticleListRequest, opts ...client.CallOption) (*ArticleListResponse, error)
}

type articleServiceClient struct {
	c           client.Client
	serviceName string
}

func NewArticleServiceClient(serviceName string, c client.Client) ArticleServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "articleservice"
	}
	return &articleServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *articleServiceClient) ArticleList(ctx context.Context, in *ArticleListRequest, opts ...client.CallOption) (*ArticleListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "ArticleService.ArticleList", in)
	out := new(ArticleListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ArticleService service

type ArticleServiceHandler interface {
	ArticleList(context.Context, *ArticleListRequest, *ArticleListResponse) error
}

func RegisterArticleServiceHandler(s server.Server, hdlr ArticleServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ArticleService{hdlr}, opts...))
}

type ArticleService struct {
	ArticleServiceHandler
}

func (h *ArticleService) ArticleList(ctx context.Context, in *ArticleListRequest, out *ArticleListResponse) error {
	return h.ArticleServiceHandler.ArticleList(ctx, in, out)
}

func init() { proto.RegisterFile("article.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0x9a, 0x90, 0x72, 0x11, 0x1d, 0xae, 0x1d, 0xac, 0x4e, 0x91, 0xa7, 0x4c, 0x19,
	0xca, 0x04, 0x5b, 0x25, 0xc6, 0x4e, 0xe6, 0x17, 0x04, 0xe7, 0x84, 0x4e, 0x54, 0xb5, 0xb1, 0x0f,
	0x06, 0x7e, 0x3d, 0xc2, 0x71, 0x51, 0x11, 0x4c, 0xf6, 0x7b, 0xcf, 0x7a, 0x9f, 0xef, 0xe0, 0x76,
	0x0c, 0xc2, 0xf6, 0x48, 0x83, 0x0f, 0x4e, 0x9c, 0x7e, 0x85, 0x66, 0x3f, 0x1b, 0xb8, 0x82, 0x92,
	0x27, 0x55, 0x74, 0x45, 0x5f, 0x9b, 0x92, 0x27, 0xdc, 0x40, 0x2d, 0x2c, 0x47, 0x52, 0x65, 0x57,
	0xf4, 0x37, 0x66, 0x16, 0xd8, 0x41, 0x3b, 0x51, 0xb4, 0x81, 0xbd, 0xb0, 0x3b, 0xa9, 0x45, 0xca,
	0x2e, 0x2d, 0x54, 0xd0, 0xd8, 0x40, 0xa3, 0xec, 0x45, 0x55, 0x29, 0x3d, 0x4b, 0xfd, 0x08, 0x98,
	0x61, 0x07, 0x8e, 0x62, 0xe8, 0xed, 0x9d, 0xa2, 0x20, 0x42, 0xe5, 0xc7, 0x17, 0xca, 0xe4, 0x74,
	0xc7, 0x2d, 0x2c, 0xbf, 0xcf, 0xc8, 0x9f, 0x33, 0xbe, 0x36, 0x3f, 0x5a, 0xdf, 0xc3, 0xfa, 0x57,
	0x4b, 0xf4, 0xee, 0x14, 0x09, 0x35, 0x34, 0x79, 0x34, 0x55, 0x75, 0x8b, 0xbe, 0xdd, 0x2d, 0x87,
	0xfc, 0xcc, 0x9c, 0x83, 0xdd, 0x01, 0x56, 0xd9, 0x7b, 0xa2, 0xf0, 0xc1, 0x96, 0xf0, 0x01, 0xda,
	0x8b, 0x32, 0x5c, 0x0f, 0x7f, 0x3f, 0xb8, 0xdd, 0x0c, 0xff, 0xf0, 0xf4, 0xd5, 0xf3, 0x75, 0x5a,
	0xe1, 0xdd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde, 0x3d, 0xd3, 0x3b, 0x53, 0x01, 0x00, 0x00,
}
